name: Node.js Express Web App to Linux on Azure

on:
  push:
    branches:
      - main

env:
  WEB_APP_NAME: 'work-centre-api'
  VM_IMAGE_NAME: 'ubuntu-18.04'

jobs:
  build:
    runs-on: ${{ env.VM_IMAGE_NAME }}
    steps:
      - name: 'Checkout code'
        uses: actions/checkout@v2

      - name: 'Install Node.js'
        uses: actions/setup-node@v2
        with:
          node-version: '18.x'

      - name: 'Install dependencies'
        run: npm install
        working-directory: ./work-centre-api

      - name: 'Archive files'
        uses: actions/upload-artifact@v2
        with:
          name: 'drop'
          path: ./work-centre-api

  deploy:
    needs: build
    runs-on: ${{ env.VM_IMAGE_NAME }}
    steps:
      - name: 'Download artifact'
        uses: actions/download-artifact@v2
        with:
          name: 'drop'

      - name: 'Login to Azure'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: 'Set Azure Web App'
        uses: azure/webapps-settings@v1
        with:
          app-name: ${{ env.WEB_APP_NAME }}
          node-version: '18.x' 

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.WEB_APP_NAME }}
          package: drop/work-centre-api
          start-up-command: 'npm start'
