name: Deploy Node.js to Azure Web App

on:
  [push]

env:
  AZURE_WEBAPP_NAME: work-centre    # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: './work-centre-ui/dist/work-centre-ui'      # set this to the path to your web app project
  NODE_VERSION: '18.12.0'                # set this to the node version to use

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ env.NODE_VERSION }}
    - name: npm install and build
      run: |
        cd work-centre-ui  # navigate to the Angular project folder
        npm install
        npm run build
    - name: 'Deploy to Azure WebApp'
      uses: azure/webapps-deploy@v1
      with: 
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
