name: Node.js CI with Azure Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm ci

    - name: Build
      working-directory: ./work-centre-api
      run: npm run build

    - name: Azure Web App Deploy
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'work-centre-api'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_SERVER }}
        package: ./work-centre-api/dist

