name: Build and deploy Angular + Node.js app to Azure Web App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Show contents of directories
        run: |
          ls -R work-centre-api
          ls -R work-centre-ui/work-centre/dist

      - name: Set up Node.js version
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Angular CLI
        run: npm install -g @angular/cli@latest

      - name: Install Node.js dependencies
        working-directory: work-centre-api
        run: npm install

      - name: Build Angular app
        working-directory: work-centre-ui/work-centre
        run: |
          npm install
          ng build --configuration=production

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: app-artifact
          path: |
            ./work-centre-api
            ./work-centre-ui/work-centre/dist/work-centre

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: app-artifact
          
      - name: Check az CLI version
        run: az --version

#       - name: Azure Login
#         uses: azure/login@v1
#         with:
#           creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'work-centre'
          slot-name: 'production'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ${{ github.workspace }}/work-centre-api
