name: Server Azure Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy-backend:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14.x'

    - name: Install dependencies
      run: |
        cd work-centre-api
        npm install
    - name: Build the app
      run: |
        cd work-centre-api
        npm run build
    - name: Archive production build
      uses: actions/upload-artifact@v2
      with:
        name: star-jobs-api
        path: work-centre-api/dist

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: star-jobs-api
        publish-profile: ${{ secrets.PUBLISH_PROFILE_API }}
        package: work-centre-api/dist
